---
# - name: Install CKAN source to virtualenv
#   pip: name='git+https://github.com/ckan/ckan.git@ckan-2.2#egg=ckan' virtualenv=/usr/lib/ckan/default virtualenv_site_packages=no

# - name: Install Python Requiements
#   pip: requirements=/usr/lib/ckan/default/src/ckan/requirements.txt virtualenv=/usr/lib/ckan/default virtualenv_site_packages=no

# - name: Start DB Cluster
#   command: /etc/init.d/postgresql start

- name: Create DB
  sudo_user: postgres
  postgresql_db: name=ckan_default
               encoding='UTF-8'
               lc_collate='en_US.UTF-8'
               lc_ctype='en_US.UTF-8'
               template='template0'
               login_password=pass

- name: Create Database User
  sudo_user: postgres
  postgresql_user: db=ckan_default user=ckan_default password=pass

- name: Create site directory
  file: path=/etc/ckan/default state=directory owner=vagrant

# - name: Create CKAN config file
#   command: /usr/lib/ckan/default/bin/paster make-config ckan /etc/ckan/default/development.ini

- name: Copy Jetty configuration to remote host
  copy: src=roles/common/files/jetty dest=/etc/default/jetty

- name: Start Jetty Server
  service: name=jetty state=started

- name: Backup Solr schema
  command: mv /etc/solr/conf/schema.xml /etc/solr/conf/schema.xml.bak

# Update to use file module
- name: Replace Solr schema.xml with symlink to CKAN schema file
  command: ln -s /usr/lib/ckan/default/src/ckan/ckan/config/solr/schema.xml /etc/solr/conf/schema.xml

- name: Restart Jetty Server
  service: name=jetty state=restarted

- name: Initialize CKAN database
  command: chdir=/etc/ckan/default /usr/lib/ckan/default/bin/paster --plugin=ckan db init

# Update to use file module
- name: Link to who.ini
  command: ln -s /usr/lib/ckan/default/src/ckan/who.ini /etc/ckan/default/who.ini

- name: Create production.ini
  command: cp /etc/ckan/default/development.ini /etc/ckan/default/production.ini 

- name: Copy Apache WSGI file
  copy: src=roles/common/files/apache.wsgi dest=/etc/ckan/default/apache.wsgi

- name: Copy Apache configuration file
  copy: src=roles/common/files/ckan_default dest=/etc/apache2/sites-available/ckan_default

- name: Copy Nginx configuration file
  copy: src=roles/common/files/ckan_default_nginx dest=/etc/nginx/sites-available/ckan_default

- name: Enable CKAN site
  command: a2ensite ckan_default

- name: Enable CKAN
  command: ln -s /etc/nginx/sites-available/ckan_default /etc/nginx/sites-enabled/ckan_default

- name: Reload Apache2
  service: name=apache2 state=reloaded

- name: Reload Nginx
  service: name=nginx state=reloaded

- name: Update NameVirtualPort port
  lineinfile: dest=/etc/apache2/ports.conf regexp='^NameVirtualHost' line='NameVirtualHost *:8080' backrefs=yes

- name: Update Listen port
  lineinfile: dest=/etc/apache2/ports.conf regexp='^Listen 80' line='Listen 8080' backrefs=yes

- name: Reload Apache2
  service: name=apache2 state=reloaded

- name: Reload Nginx
  service: name=nginx state=reloaded