---
- name: Create upload directory
  file: path=/var/lib/ckan/default state=directory owner=www-data mode=0700

- name: Update CKAN config
  ini_file: dest=/etc/ckan/default/production.ini section=app:main option=ckan.storage_path value=/var/lib/ckan/default backup=yes

- name: Reload Apache
  service: name=apache2 state=reloaded