---
- name: Create upload directory
  file: path=/var/lib/ckan/default state=directory owner=www-data mode=0700

- name: Update CKAN config
  lineinfile: dest=/etc/ckan/default/production.ini regexp='^#ckan.storage_path' line='ckan.storage_path = /var/lib/ckan/default' backrefs=yes

- name: Reload Apache
  service: name=apache2 state=reloaded