---
- hosts: all
  user: vagrant
  sudo: true

  tasks:

  - name: General | Copy SSH Keypair
    copy: src=/home/sean/.ssh/{{ item }} dest=/home/vagrant/.ssh/{{ item  }} owner=vagrant
    with_items:
    - id_rsa_vagrant
    - id_rsa_vagrant.pub

  - name: General | Install Required Packages
    apt: pkg={{ item }} state=present update_cache=yes
    with_items:
    - git-core
    - libpq-dev
    - openjdk-6-jdk
    - postgresql
    - python-dev
    - python-pip
    - python-psycopg2
    - python-virtualenv
    - solr-jetty

  - name: CKAN | Install CKAN source to virtualenv
    pip: name='git+https://github.com/ckan/ckan.git@ckan-2.2#egg=ckan' virtualenv=/usr/lib/ckan/default virtualenv_command=/usr/lib/ckan/default/bin/activate virtualenv_site_packages=no

  - name: CKAN | Install Python Requiements
    pip: requirements=/usr/lib/ckan/default/src/ckan/requirements.txt virtualenv=/usr/lib/ckan/default virtualenv_command=/usr/lib/ckan/default/bin/activate virtualenv_site_packages=no

  - name: PostgreSQL | Start DB Cluster
    command: /etc/init.d/postgresql start

  - name: CKAN | Create DB
    sudo_user: postgres
    postgresql_db: name=ckan_default
                   encoding='UTF-8'
                   lc_collate='en_US.UTF-8'
                   lc_ctype='en_US.UTF-8'
                   template='template0'
                   login_password=pass

  - name: CKAN | Create Database User
    sudo_user: postgres
    postgresql_user: db=ckan_default user=ckan_default password=pass

  - name: CKAN | Create site directory
    file: path=/etc/ckan/default state=directory owner=vagrant

  - name: CKAN | Copy development.ini to remote host
    copy: src=/home/sean/projects/github/open-data-portal/provisioning/roles/common/files/development.ini dest=/etc/ckan/default/development.ini

  # - name: CKAN | Create CKAN config file
  #   command: chdir=/etc/ckan/default /usr/lib/ckan/default/bin/paster make-config /etc/ckan/default/development.ini

  - name: CKAN | Copy Jetty configuration to remote host
    copy: src=/home/sean/projects/github/open-data-portal/provisioning/roles/common/files/jetty dest=/etc/default/jetty

  - name: CKAN | Start Jetty Server
    service: name=jetty state=started

  - name: CKAN | Backup Solr schema
    command: mv /etc/solr/conf/schema.xml /etc/solr/conf/schema.xml.bak

  - name: CKAN | Replace Solr schema.xml with symlink to CKAN schema file
    file: src=/usr/lib/ckan/default/src/ckan/ckan/config/solr/schema.xml dest=/etc/solr/conf/schema.xml

  - name: CKAN | Restart Jetty Server
    service: name=jetty state=restarted

  - name: CKAN | Initialize CKAN database
    sudo_user: postgres
    command: chdir=/etc/ckan/default /usr/lib/ckan/default/bin/paster --plugin=ckan db init