#!/usr/bin/env python
import urllib2
import urllib
import json
import pprint

# Put the details of the dataset we're going to create into a dictionary
dataset_dictionary = {
    'name': 'api-demo',
    'title': 'API Demo Dataset',
    'author': 'Sean Baskin',
    'author_email': 'baskin_s@chattanooga.gov',
    'maintainer': 'Nate Hill',
    'maintainer_email': 'hill_n@lib.chattanooga.gov',
    'license_id': 'cc-by'
}

# Use the json module to dump the dictionary to a string
dataset_dictionary_string = urllib.quote(json.dumps(dataset_dictionary))

# We'll use the package_create function to create a new dataset
http_request = urllib2.Request('http://opendata.chattlibrary.dev:8080/api/3/action/package_create')

'''
Creating a dataset requires an authorization header.

This API key is generated by CKAN and associated with my account. 
It is not a live key and only works on my CKAN instance on my VM.
'''
http_request.add_header('Authorization', '0a5f3e00-b32c-426e-b2cd-f2c821350b29')

# Make the HTTP request.
http_response = urllib2.urlopen(http_request, dataset_dictionary_string)

# TODO
assert http_response.code == 200

# Use the json module to load CKAN's response into a dictionary.
http_response_dict = json.loads(http_response.read())

# TODO
assert response_dict['success'] is True

# package_create returns the created package as its result.
created_package = http_response_dict['result']

# TODO
pprint.pprint(created_package)