#!/usr/bin/env python
import requests

'''
This API key is generated by CKAN and associated with my account. 
It is not a live key and only works on my CKAN instance on my VM.
'''
requests.post('http://opendata.chattlibrary.dev:8080/api/3/action/resource_create',
              data={"package_id":"api-demo"},
              headers={"X-CKAN-API-Key": "0a5f3e00-b32c-426e-b2cd-f2c821350b29"},
              files=[('upload', file('/home/sean/projects/data/attendanceandgraduationschool.csv'))])